# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 20:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=60)),
                ('string', models.TextField(help_text='string describing the complete genotype unambiguously')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenotypeMetaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateField(auto_now=True)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/user/Dropbox/workspace/labdb/files/'), upload_to='meta/genotype/')),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('attached_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_files', to='genetics.Genotype')),
            ],
        ),
    ]
