# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DataType'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='prot_mods',
            field=models.ManyToManyField(blank=True, to='assays.ProtocolModifier', verbose_name='protocol_modifiers'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='samples',
            field=models.ManyToManyField(blank=True, through='assays.Assay', to='experiments.Sample', verbose_name='protocol assays'),
        ),
        migrations.AddField(
            model_name='assay',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assay',
            name='protocol',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assays', to='assays.Protocol'),
        ),
        migrations.AddField(
            model_name='assay',
            name='sample',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assays', to='experiments.Sample'),
        ),
    ]
