# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0003_auto_20160808_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='description',
        ),
        migrations.RemoveField(
            model_name='protocolmetafile',
            name='description',
        ),
        migrations.AddField(
            model_name='protocol',
            name='desc',
            field=models.TextField(default='', max_length=2000, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocolmetafile',
            name='desc',
            field=models.TextField(blank=True, max_length=2000, verbose_name='description'),
        ),
    ]
