# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 20:56
from __future__ import unicode_literals

import data.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/user/Dropbox/workspace/labdb/files/'), upload_to=data.models.get_storage_path)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data', to='assays.Assay')),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_extension', models.CharField(max_length=10)),
                ('is_raw', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.DataType'),
        ),
    ]
