# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='assay',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='data', to='assays.Assay'),
        ),
        migrations.AlterField(
            model_name='data',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_set', to='data.DataType'),
        ),
    ]
